version: "3"
services:
  redis:
    image: redis:latest
    container_name: cache
    ports:
      - 6379:6379
  # search-rest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     ENV_NAME: dev
  #   ports:
  #     - 3000:3001
